version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: "imaya-rabbitmq"
    volumes:
      - /tmp/rq-data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      #- RABBITMQ_MNESIA_DIR=/var/
  pyrq-web-app:
    image: composedpyrqsvc_pyrq-web-app
    #build: rest-app
    depends_on:
     - "rabbitmq"
    ports:
     - "4000:80"
    volumes:
     - /Users/imayakulothungan/exper/docker/composed-pyrq-svc/rest-app:/myapp
  pyrq-cons-app:
    #build: consumer-app
    image: composedpyrqsvc_pyrq-cons-app
    depends_on:
     - "rabbitmq"
    ports:
     - "5000:80"
    deploy:
      replicas: 2
